name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-11]
        include:
          - phalcon: 3.4
            php: '7.3'

          - phalcon: 4.0.0
            php: '7.4'

          - phalcon: 4.0.2
            php: '7.4'

          - phalcon: 4.0.3
            php: '7.4'

          - phalcon: 4.0.4
            php: '7.4'

          - phalcon: 4.0.5
            php: '7.4'

          - phalcon: 4.0.6
            php: '7.4'

          - phalcon: 4.1.0
            php: '7.4'

          - phalcon: 4.0RC2
            php: '7.3'

          - phalcon: 4.0rc3
            php: '7.3'

          - phalcon: 73_4.0.0
            php: '7.3'
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1

    name: Building Phalcon@${{ matrix.phalcon }} PHP-${{ matrix.php }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Add Phalcon Tap
      run: brew tap phalcon/extension .

    - name: Install Phalcon
      run: |
        export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
        brew install phalcon --build-from-source

    - name: Build Formula
      run: |
        brew install --build-bottle phalcon
        brew bottle --json --no-rebuild phalcon

    - name: Force PHP linking
      run: brew link -f --overwrite php@${{ matrix.php }}

    - name: Check PHP
      run: |
        php -v
        php --ini

    - name: Testing ini values
      run: |
        php --ri psr
        php --ri phalcon
        php -r "if(! extension_loaded('psr')) {throw new Exception('psr not found');}"
        php -r "if(! extension_loaded('phalcon')) {throw new Exception('phalcon not found');}"
